### ISSUE TITLE
Rainy and foggy cityscapes dataset

### ISSUE THREAD

**Issue by Hectoor** [naver/oasis#1]
Hello! I was wondering if the rainy and foggy Cityscape datasets can be directly downloaded from the official website. Or these datasets are generated by some methods? Could you please provide some information on how to obtain these datasets?

**Comment by Hectoor** [comment]
Actually, I found rainy and foggy datasets on the official website, which are called leftImg8bit_trainval_rain.zip (21GB) and leftImg8bit_trainval_foggyDBF.zip (20GB)], respectively. But I'm not sure if these are the two datasets used in your work.

**Comment by ricvolpi** [comment]
Hey, indeed, those are the ones we use. We selected a subset of images (specific fog/rain rendering parameters) -- see args from [this line](https://github.com/naver/oasis/blob/19232eadbbda1eefb79eb7721d7068b61b1e73c8/main_adapt.py#L871) on.

If you use our dataloaders, you should not have issues loading the same images we used.

**Comment by cht619** [comment]
for rain dataset i get 70 miou？
